### ISSUE TITLE
ytnef error when trying to parse file with attachments with filename longer than 100 chars

### ISSUE THREAD

**Issue by mgiacomoli** [Yeraze/ytnef#107]
The limit configured for attachment filename is too low. It's currently configured to 100 bytes, while as per [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry), the maximum filename size is 256 bytes and filepath size is 260 bytes.

In pull request #106 the limit is increased to 260 bytes

**Comment by QHivert** [comment]
Hello @Yeraze ,
I have test and validate this fis fix, could you make a new release so we can build our package with a proper version ?

**Comment by Yeraze** [comment]
Done! https://github.com/Yeraze/ytnef/releases/tag/v2.1.2
