### ISSUE TITLE
ChangeLog update for 1.9.1

### ISSUE THREAD

**Issue by jmallach** [Yeraze/ytnef#30]
Hi Yeraze,

I've seen the 1.9.1 release and was about to package it for Debian, when I had a look at the individual commits from #27. Well, some of those seem bad enough to even warrant some CVEs being issued.

But at least, the ChangeLog should be updated to mention these issues individually, and have some [SECURITY] markers all around the place, even with <blink> if it were valid markup.

If #28 is fixed, I think that could also make up for a 1.9.2.

Thanks!

**Comment by jmallach** [comment]
You can now add the CVE numbers for all the individual issues. See https://security-tracker.debian.org/tracker/source-package/libytnef

**Comment by Yeraze** [comment]
Please check #32

**Comment by Yeraze** [comment]
Incorporated into 1.9.2 release
