### ISSUE TITLE
possible to choose codex?

### ISSUE THREAD

**Issue by Roland8049** [Yeraze/ytnef#53]
I'm in a German environment. TNEF don't display special characters as e.g. Umlaut correctly. Is there a way to change the codex to Unicode (UTF-8)? This is not crucial, more a nice to have feature.

**Comment by ohwgiles** [comment]
I think attachments retain their source encoding. Are you talking about properties? Can you provide a tnef file that reproduces the issue using the `ytnefprint` program?

**Comment by Roland8049** [comment]
Thanks, Oliver. Actually I can't reproduce the problem. At this time German special characters seem to display ok. I'm going to close the thread.
Thanks again and greetings from Switzerland!
