### ISSUE TITLE
SIGSEGV in MAPIFindUserProp

### ISSUE THREAD

**Issue by evintila** [Yeraze/ytnef#67]
Command: "ytnef -v crash1_1"
Output:
Starting program: /usr/local/bin/ytnef -v crash1_1
Attempting to parse crash1_1...
Out of Memory at ytnef.c : 425
ERROR Parsing MAPI block

Program received signal SIGSEGV, Segmentation fault.

gdb call trace:
#0  MAPIFindUserProp (p=p@entry=0x7fffffffd878, ID=ID@entry=2359326) at ytnef.c:1217
#1  0x00000000004043ca in ProcessTNEF (TNEF=...) at main.c:166
#2  0x0000000000401012 in main (argc=3, argv=0x7fffffffdcf8) at main.c:129

version 1.9.2, Ubuntu 16.04, gcc 5.4.0
found using afl

[crash1_1.zip](https://github.com/Yeraze/ytnef/files/2097966/crash1_1.zip)

**Comment by ohwgiles** [comment]
fixed in #71

**Comment by Yeraze** [comment]
Released in https://github.com/Yeraze/ytnef/releases/tag/v1.9.3
