### ISSUE TITLE
SIGSEGV in TNEFFreeMapiProps: Out of Memory

### ISSUE THREAD

**Issue by evintila** [Yeraze/ytnef#69]
Command: "ytnef -v crash3"
Output:
Starting program: /usr/local/bin/ytnef -v crash3
Attempting to parse crash3...
Out of Memory at ytnef.c : 448
zappa_av1.jpg

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bc4429 in TNEFFreeMapiProps (p=p@entry=0x609710) at ytnef.c:978

gdb call trace:
#0  0x00007ffff7bc4429 in TNEFFreeMapiProps (p=p@entry=0x609710) at ytnef.c:978
#1  0x00007ffff7bc4593 in TNEFFreeAttachment (p=p@entry=0x6096a0) at ytnef.c:971
#2  0x00007ffff7bc46e8 in TNEFFree (TNEF=TNEF@entry=0x7fffffffd930) at ytnef.c:958
#3  0x0000000000401021 in main (argc=3, argv=0x7fffffffdcf8) at main.c:130

version 1.9.2, Ubuntu 16.04, gcc 5.4.0
found using afl
[crash3.zip](https://github.com/Yeraze/ytnef/files/2097967/crash3.zip)

**Comment by ohwgiles** [comment]
fixed in #71

**Comment by Yeraze** [comment]
Released in https://github.com/Yeraze/ytnef/releases/tag/v1.9.3
