### ISSUE TITLE
SIGSEGV in TNEFFreeMapiProps (3)

### ISSUE THREAD

**Issue by evintila** [Yeraze/ytnef#70]
Command: "ytnef -v crash4"
Output:
Attempting to parse crash4...
Out of Memory at ytnef.c : 483
ERROR Parsing MAPI block

Program received signal SIGSEGV, Segmentation fault.

gdb call trace:
#0  0x00007ffff7bc4429 in TNEFFreeMapiProps (p=p@entry=0x7fffffffdb28) at ytnef.c:978
#1  0x00007ffff7bc46cb in TNEFFree (TNEF=TNEF@entry=0x7fffffffd930) at ytnef.c:954
#2  0x0000000000401021 in main (argc=3, argv=0x7fffffffdcf8) at main.c:130

version 1.9.2, Ubuntu 16.04, gcc 5.4.0
found using afl
[crash4.zip](https://github.com/Yeraze/ytnef/files/2097976/crash4.zip)

**Comment by ohwgiles** [comment]
fixed in #71

**Comment by Yeraze** [comment]
Released in https://github.com/Yeraze/ytnef/releases/tag/v1.9.3
